### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by zvezdochiot** [indigo-astronomy/novas#2]
https://github.com/indigo-astronomy/novas/blob/07472278932a30fc1dbdc4afc5dca0ca810cbfca/README.txt#L44

❓ Maybe combine with PDM 1.0? (https://github.com/Geo-Linux-Calculations/geofindkey/blob/master/LICENSE)

**Comment by polakovic** [comment]
Sorry, I don't understand... Why do you want to combine the licenses?

**Comment by zvezdochiot** [comment]
Hi @polakovic .

I just want to see if I understood the README text correctly? In my opinion, this text corresponds in a certain way to PDM 1.0. But there is no separate text LICENCE, hence the question. What is the license for this code?

PS: Perhaps the more appropriate license is BSD, but which one?

**Comment by polakovic** [comment]
Well, it is not our software :) This package contains exactly what JPL released, we didn't touched it. I don't think we should add any license conditions.

**Comment by zvezdochiot** [comment]
Hi @polakovic .

Hmm. I’m just trying to bring the README into a form that is accepted for such projects. But the attempt seems to be unsuccessful.

**Comment by toddcarnes** [comment]
For the record, the JPL did not release this software. The U.S. Naval Observatory released it.
