### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by zvezdochiot** [indigo-astronomy/novas#3]
See https://github.com/Geo-Linux-Calculations/novas/releases

**Comment by polakovic** [comment]
It is the version we use in INDIGO, isn't it?

**Comment by zvezdochiot** [comment]
@polakovic say:
>It is the version we use in INDIGO, isn't it?

Yes. After PR, nothing changed.

**Comment by zvezdochiot** [comment]
Overdue.
